% Q4

% Some code may already be provided below
% DO NOT clear, close or clc inside this script
% Apply good programming practices
%
% Name : Khanh Nguyen
% ID   : 32498349
% Date Modified : Sunday 10th October 2021

fprintf('\n Q4 \n\n')
%%
% (i)
fprintf(['The total amount of gold in grams can be given by an equation that\n',...
'considers the amount of gold that can be extracted per cubic metres and the\n',...
'the amount of cubic metres of dirt that is examined under the 5 hours\n',...
'specified.\n\n'])

fprintf(['The amount of gold that can be recovered per cubic metres is given by:\n',...
'the recovery rate of gold * the concentration of gold per cubic metres.\n',...
'This is equal to (R) * (max_c), where R is the recovery equation from Q2 and\n',...
'max_c is assumed to be the concentration of gold from the project brief.\n',...
'Ultimately, substituing everything, it is equal to:\n',... 
'%1.4f*(s/(s+%1.4f)) * %1.4f, where s is the spinning time.\n\n'],a,b,max_c)

fprintf(['The amount of cubic metres of dirt recovered under 5 hours is given by:\n',...
'the amount of cycles in 5 hours * the amount of dirt per cycles.\n\n',...
'The amount of cycles in 5 hours must be consider by taking the total time\n',...
'divided by the time per cycle. Furthermore, we know the time per cycle is:\n',...
'time (in seconds) per cycle = spinning time + digging time + cleaning time\n',...
'                            = 3(spin_time) + 3(30seconds) + 2minutes\n',...
'                            = 3(spin_time) + 90 + 120 [all in seconds]\n',...
'NOTE: We times 3 for the digging time and spinning time because, we consider\n',...
'1 cycle to be three times shovel and spinning so we can include the clean time.\n',...
'Also, we know that the total time is 5 hours, which is equal to 18000 seconds.\n',...
'Hence, we can find the amount of cycles that happens in 5 hours to be given by:\n',...
'number of cycle (in 5 hours) = 18000/(3spin_time + 210)\n\n',...
'Ultimately, we have:\n',...
'the amount of dirt (covered in 5 hours) = 18000/(3spin_time + 210) * (15/1000)\n',...
'NOTE: We divide the 5 by 1000 because the amount of dirt per cycle is given\n',...
'in Litres; therefore, we divide by 1000 to turn it into units of cubic metres.\n\n'])

fprintf(['From all the information, we finally have the amount of gold found in 5 hours is given by:\n',...
'total gold (5 hours) = %1.4f*(s/(s+%1.4f)) * %1.4f * 18000/(3s + 210) * (15/1000), where s is spinning time.\n'],a,b,max_c)

% (ii)
s_t = 0:1:100;
total_gold = (a.*s_t./(s_t+b)).*max_c.*18000./(3*s_t+210).*(15/1000);
[max_gold,index] = max(total_gold);
max_s_t = s_t(index);
max_s_t_rec = R(s==max_s_t);
fprintf(['\nThe optimal spinning time to maximise gold after 5 hours of work is %1.0f seconds, and\n',...
'the corresponding recovery rate is %1.3f.\n'],max_s_t,max_s_t_rec)

% (iii)
fprintf('\nThe amount of gold we got after 5 hours and using the optimum spinning time is %1.3f grams.\n\n',max_gold) 

% (iv)
per_hour_rate = max_gold/5 * 80; %(grams/hour) * (dollars/gram) = (dollars/hour)
fprintf(['You would earn $%1.1f per hour. This would not be a very attractive job because it has very low returns\n',...
'and it is below minimum wage.\n'],per_hour_rate)

% (v)
ratio_earn = round(per_hour_rate/productivity,3,'significant');
fprintf(['\nThe ratio of the spiral seperator use to that of the most efficient friend is %1.2f.\n',...
'This shows that using the spiral separator and the knowledge of the richest deposit\n',...
'on the beach has a slight advantage in finding gold and making money with 24 percent\n',...
'more money made per hour in terms of the money made by the most efficient person.\n'],ratio_earn)
